name: CI Build with tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 15, 17 ]
        distribution: [ zulu ]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        id: baseline_java
        with:
          java-version: 15
          distribution: ${{ matrix.distribution }}
      - uses: actions/setup-java@v2
        id: build_java
        with:
          java-version: ${{ matrix.java-version }}
          distribution: ${{ matrix.distribution }}
          cache: gradle
      - name: Build
        env:
          BASELINE_JAVA_HOME: ${{ steps.baseline_java.outputs.path }}
          BUILD_JAVA_HOME: ${{ steps.build_java.outputs.path }}
        run: |
          ./src/scripts/gh-action-ci.sh ${{ matrix.java-version }}